// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtymC1oNk8IQJP1GrxiFqSKUsvQ9LWRUk',
    appId: '1:143551172384:web:11a0559d5cd6eca48dd145',
    messagingSenderId: '143551172384',
    projectId: 'book-my-venue-dev',
    authDomain: 'book-my-venue-dev.firebaseapp.com',
    databaseURL: 'https://book-my-venue-dev-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'book-my-venue-dev.firebasestorage.app',
    measurementId: 'G-RL4Q74XFJ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJNOzRKgHNUNx9eIVq7TkoDVsh5V9nqaA',
    appId: '1:143551172384:android:0fd22380371ba4a48dd145',
    messagingSenderId: '143551172384',
    projectId: 'book-my-venue-dev',
    databaseURL: 'https://book-my-venue-dev-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'book-my-venue-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC96SN8NjBaaw8S1EtEMVEW3DzyD_qtq3g',
    appId: '1:143551172384:ios:a8e54fddcc64b6f38dd145',
    messagingSenderId: '143551172384',
    projectId: 'book-my-venue-dev',
    databaseURL: 'https://book-my-venue-dev-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'book-my-venue-dev.firebasestorage.app',
    iosClientId: '143551172384-qjr5kt6dnc8h3fl4s006uq6imhjfbo2d.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminApp',
  );
}
